### ISSUE TITLE
BUG Incorrect type inspection on many_many through

### ISSUE THREAD

**Issue by tractorcow** [silbinarywolf/silverstripe-phpstan#13]
As per comment at https://github.com/silverstripe/recipe-cms/issues/12#issuecomment-394942073

https://github.com/silbinarywolf/silverstripe-phpstan/blob/7fadf204193dcfa313666509a3e5d20098ab970a/src/Reflection/MethodClassReflectionExtension.php#L129-L138

The type of the list is not the 'through' array value. That's the 'internal type' only; You'll need to use both 'through' and 'to' to get the actual list class type.

See DataObjectSchema for how we do this internally.

```php
// Normal many-many
            if ($manyManySpec === $parentClass) {
                return $inverseComponentName;
            }
            // many-many through, inspect 'to' for the many_many
            if (is_array($manyManySpec)) {
                $toClass = $this->hasOneComponent($manyManySpec['through'], $manyManySpec['to']);
                if ($toClass === $parentClass) {
                    return $inverseComponentName;
                }
            }
```

Where you have `$type = $type['through'];` you'll actually need to do deep inspection on the through class to pull the type of the has_one property specified by `$type['to']`.

Hope that helps. :)

**Comment by sminnee** [comment]
@silbinarywolf it'd be great if you could confirm that this is the issue so that we can close off https://github.com/silverstripe/silverstripe-versioned/issues/155 as a misidentified error

**Comment by silbinarywolf** [comment]
@tractorcow Ah yep. You're probably correct.
@sminnee I'll investigate this weekend and confirm if the issue is on my end.

**Comment by silbinarywolf** [comment]
@tractorcow You were correct.
cc @sminnee 

My steps to confirm this were:
- I made sure to pull down the latest Recipe CMS code
- Checked for the existence of SiteTreeLink in the project
- Run the following hacky-code to test the return type of LinkTracking()
```
<?php

use SilverStripe\CMS\Model\SiteTree;

class Page extends SiteTree
{
    private static $db = [];

    private static $has_one = [];

    public function getCMSFields() {
        $fields = parent::getCMSFields();
        foreach (Page::get() as $r) {
            $r->LinkTracking()->add($r);
            foreach ($r->LinkTracking() as $record) {
                var_dump(get_class($record)); exit;
            }
        }
        return $fields;
    }
}
```
- The class type returned was `Page` and not `SiteTreeLink`.

This bug in my code has now been fixed, pushed up and tagged here:
https://github.com/silbinarywolf/silverstripe-phpstan/commit/d0feb04b8b609a30542a3ddb92c02b4025a6af00

Sorry for the false positive guys! 
I'll be sure to test things more thoroughly before raising in the future.
