### ISSUE TITLE
0.3 is great :)

### ISSUE THREAD

**Issue by grantlucas** [silbinarywolf/silverstripe-phpstan#9]
Sorry for the spam issue but I just wanted to say 0.3 is great! It resolved a bunch of false alarms Stan was reporting previously. In one of our modules it went from 300 reported issues, mostly reflection issues, down to just 14 which are actual issues.

**Comment by silbinarywolf** [comment]
@grantlucas Awesome! Thank you so much for getting things fixed up for 0.9, that was the main barrier for me.
